### ISSUE TITLE
The model `gpt-4o` does not exist or you do not have access to it

### ISSUE THREAD

**Issue by mgroth0** [shobrook/wut#14]
Getting this error:

```
File "/Users/*/.local/pipx/venvs/wut-cli/lib/python3.13/site-packages/openai/_base_client.py", line 1061, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4o` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
```

Can this be handled by trying other models automatically?

**Comment by shobrook** [comment]
Hmm I didn't realize that model wasn't available for some users. I'll add a fallback mechanism.

**Comment by shobrook** [comment]
Instead of a fallback mechanism, there's now the option to set the OpenAI model you want to use as an environment variable:

```bash
> export OPENAI_MODEL="gpt-4-turbo"
```

Choose a model you have access to and let me know if this works. Thanks!
