### ISSUE TITLE
Automatically executing commands is too dangerous

### ISSUE THREAD

**Issue by mgroth0** [shobrook/wut#15]
I noticed in your readme that you had the idea of having the commands suggested by the AI be executed automatically. This seems too dangerous, and probably is not an ethical software to be putting out there. I can see how it sounds cool at first, but in reality this will probably hurt people by accident. Certain commands if they are given the wrong arguments may delete files or do other kinds of permanent damage. I cannot imagine a scenario where this could be used safely, given the unlimited power of shell commands.

**Comment by shobrook** [comment]
I imagine the suggested command would be shown to the user first and they'd choose whether to execute it.

**Comment by shobrook** [comment]
We can avoid the copy-paste step too and simply ask the user to press Y or N to execute or reject the suggested command.
