### ISSUE TITLE
[SOLVED] /usr/bin/echo: cannot execute binary file

### ISSUE THREAD

**Issue by PieBru** [shobrook/wut#20]
Hi, awesome command!

Installed on my Arch Linux following the doc ad executed under `tmux`, it gives the error in the title, here is a screenshot:
![image](https://github.com/user-attachments/assets/3e55b13e-f663-41d4-84a0-affd345666de)

Did I miss something or may I help to solve the problem?

Thank you,
Piero

**Comment by shobrook** [comment]
Hmm interesting. Could you tell me what shell you're using please? Whatever it is, it looks like `echo` isn't a valid shell command for you.

**Comment by shobrook** [comment]
If it's bash, I just pushed a fix. Please upgrade the package to v1.0.8 and let me know if you still have issues:

```bash
> pipx upgrade wut-cli
```

**Comment by PieBru** [comment]
Using `bash` on Arch Linux.
v1.0.8 solved it.
Thank you.
Piero
